DROP TABLE IF EXISTS Review CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS ProductPhoto CASCADE;
DROP TABLE IF EXISTS VacancyTranslation CASCADE;
DROP TABLE IF EXISTS ProductTranslation CASCADE;
DROP TABLE IF EXISTS CategoryTranslation CASCADE;

DROP TABLE IF EXISTS Product CASCADE;
DROP TABLE IF EXISTS Vacancy CASCADE;
DROP TABLE IF EXISTS Brand CASCADE;
DROP TABLE IF EXISTS Review CASCADE;

DROP TABLE IF EXISTS Language CASCADE;
