app:
  host: "0.0.0.0"
  port: "8080"
  base_url: "http://64.176.71.25"

database:
  host: "127.0.0.1"
  port: "5432"
  db_name: "test"
  username: "postgres"
  password: "postgres"

log:
  level: "dev"

token:
  token_ttl: "1h"
  jwt_secret: "amdoifnrjkeworipalkdsfodjlam1o32pr0-ikmx2lp13o4ij2"
