app:
  host: "127.0.0.1"
  port: "8080"
  baseUrl: "http://64.176.71.25"

database:
  host: "127.0.0.1"
  port: "5432"
  dbName: "test1"
  username: "postgres"
  password: "postgres"

log:
  level: "dev"

token:
  tokenTTL: "1h"
  jwtSecret: "amdoifnrjkeworipalkdsfodjlam1o32pr0-imx2lp13o4ij2"