// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Brand struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
	Url  string `json:"url"`
}

type Category struct {
	ID int32 `json:"id"`
}

type Categorytranslation struct {
	CategoryID   int32  `json:"category_id"`
	LanguageCode string `json:"language_code"`
	Name         string `json:"name"`
}

type Discount struct {
	ID                 int32            `json:"id"`
	ProductID          pgtype.Int4      `json:"product_id"`
	DiscountPercentage pgtype.Numeric   `json:"discount_percentage"`
	StartDate          pgtype.Timestamp `json:"start_date"`
	EndDate            pgtype.Timestamp `json:"end_date"`
}

type Language struct {
	Code string      `json:"code"`
	Name pgtype.Text `json:"name"`
}

type Photo struct {
	ID        int32       `json:"id"`
	Url       pgtype.Text `json:"url"`
	IsMain    pgtype.Bool `json:"is_main"`
	HashColor pgtype.Text `json:"hash_color"`
}

type Product struct {
	ID          int32          `json:"id"`
	TypeProduct string         `json:"type_product"`
	RefID       int32          `json:"ref_id"`
	CategoryID  pgtype.Int4    `json:"category_id"`
	Name        string         `json:"name"`
	Price       pgtype.Numeric `json:"price"`
	IsProducer  bool           `json:"is_producer"`
	IsPainted   bool           `json:"is_painted"`
	IsPopular   bool           `json:"is_popular"`
	IsNew       bool           `json:"is_new"`
	IsGarant    interface{}    `json:"is_garant"`
	Isaqua      bool           `json:"isaqua"`
}

type Productphoto struct {
	ProductID int32 `json:"product_id"`
	PhotoID   int32 `json:"photo_id"`
}

type Producttranslation struct {
	ProductID    int32  `json:"product_id"`
	LanguageCode string `json:"language_code"`
	Description  string `json:"description"`
}

type Review struct {
	ID        int32            `json:"id"`
	Username  string           `json:"username"`
	Rating    pgtype.Int4      `json:"rating"`
	Text      string           `json:"text"`
	IsShow    interface{}      `json:"is_show"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID        int32              `json:"id"`
	Username  string             `json:"username"`
	Email     string             `json:"email"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Vacancy struct {
	ID       int32          `json:"id"`
	Isactive pgtype.Bool    `json:"isactive"`
	Salary   pgtype.Numeric `json:"salary"`
}

type Vacancytranslation struct {
	VacancyID        pgtype.Int4 `json:"vacancy_id"`
	LanguageCode     pgtype.Text `json:"language_code"`
	Title            string      `json:"title"`
	Requirements     []string    `json:"requirements"`
	Responsibilities []string    `json:"responsibilities"`
	Conditions       []string    `json:"conditions"`
	Information      []string    `json:"information"`
}
